# Numpy

> pip install numpy

In [1]:
import sys
import time
import numpy as np

# Compare native python list and numpy

## 1. Memory Size

In [2]:
SIZE = 100 

mylist = list(range(100))


# Native Python 
print(sys.getsizeof(1) * SIZE)


# Numpy Array
numpy_array = np.array(SIZE)
print(numpy_array.itemsize * SIZE) # 400 bytes --> 4x Bytes pro Integer

2800
400


## 2. Execution Time

In [9]:
SIZE = 1000000

mylist1 = range(SIZE)
mylist2 = range(SIZE)

start = time.time()
result =  [(x+y) for x,y in zip(mylist1, mylist2)]
end = time.time()

print("Time: ",  (end-start) * 1000)

Time:  140.95330238342285


In [10]:
SIZE = 1000000
array1 = np.arange(SIZE)
array2 = np.arange(SIZE)

start = time.time()
result = array1  + array2 
end = time.time()

print("Time: ",  (end-start) * 1000)

Time:  13.994216918945312


# Define Arrays

In [14]:
mylist = [ 1 , 2 ,3 ,4 ,5]
print(mylist, type(mylist))


array = np.array(mylist)
print(array, type(array))


array1 = np.array( [ 1 , 2 ,3 ,4 ,5])
print(array1, type(array1))


# define a multi-deminsional array
array2 = np.array([ [1, 2], [3,4]])
print(array2)

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>
[1 2 3 4 5] <class 'numpy.ndarray'>
[[1 2]
 [3 4]]


In [16]:
# Define with specific data type
array_1 = np.array([1,2,3,4,5], dtype = np.float64 )
print(array_1)

array_1 = np.array([1,2,3,4,5], dtype = np.int32 )
print(array_1)

[1. 2. 3. 4. 5.]
[1 2 3 4 5]


# Array Information

In [23]:
array_1 = np.array([1,2,3,4,5])
print(array_1)

print(array_1.shape)
print(array_1.ndim)
print(array_1.size) # 5x items
print(array_1.dtype) # 5x items
print(array_1.itemsize) # 4x bytes for each item

[1 2 3 4 5]
(5,)
1
5
int32
4


In [28]:
# define a multi-deminsional array
array_2 = np.array([ [1.1, 2.2], [3.3, 4.4]])
print(array_2.shape)
print(array_2.ndim)
print(array_2.size)
print(array_2.dtype)
print(array_2.itemsize)


(2, 2)
2
4
float64
8


# Mathematical Operations

In [30]:
a = np.arange(10) # 0->9
b = np.arange(10) # 0->9


print(a + b)
print(a - b)
print(a * b)
print(a / b)

print()


print(np.sqrt(a))

[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


C:\Users\MD\AppData\Local\Temp\ipykernel_20176\1376260262.py:8: RuntimeWarning: invalid value encountered in divide
  print(a / b)


# Functions

In [36]:
a = np.arange(10) # 0->9
b = np.arange(10) # 0->9
c = np.array([ [ 1, 2], [3,4], [5,6]])

# Array Methods
print(a.min())
print(a.max())
print(a.mean())
print(a.sum())

print(c.sum()) # 1 + 2 + 3 + 4 + 5 + 6  


""" 
axis = 0 : columns
axis = 1 : rows
"""
print(c.sum(axis= 0))  # over the columns
print(c.sum(axis= 1))  # over the rows


# Sorting
a = np.array([5,3,8,1,9,3])

a.sort()
print(a)


# Rounding
a = np.array([5.0, 3.3, 2.123])
print(a.round(decimals= 2))

0
9
4.5
45
21
[ 9 12]
[ 3  7 11]
[1 3 3 5 8 9]
[5.   3.3  2.12]


# Accessing Items -> Slicing

In [107]:
c = np.array([ [ 1, 2], [3,4], [5,6]])

print(c.shape) # 3x rows, 2xcolumns

print(c[0]) # [1 2]
print(c[2]) # [5 6]

print(c[0:2]) # 

# Access Specific Item
print(c[1,1]) # #  

# Range
print()
print(c)
print()
print(c[0:2, 1:2])
print(c[0:2, 0:2])


(3, 2)
[1 2]
[5 6]
[[1 2]
 [3 4]]
4

[[1 2]
 [3 4]
 [5 6]]

[[2]
 [4]]
[[1 2]
 [3 4]]


# Generate Data

In [50]:
a = np.arange(30)
b = np.arange(10,30)


print(a)
print(b)

zeros = np.zeros((3, 4))
print(zeros)

ones = np.ones((3, 4))
print(ones)

numbers = np.linspace(1, 5, 50) # 50x numbers between 1 and 5, equally spaced
print(numbers)


numbers2 = np.full((2,3) ,   5)
print(numbers2)


numbers2 = np.full((6, ) ,   5)
print(numbers2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]
[[5 5 5]
 [5 5 5]]
[[5]
 [5]
 [5]
 [5]
 [5]
 [5]]


# Reshaping

In [57]:
a = np.array( [
                [1,2],
                [3,4],
                [5,6]
              ]  
            )

print("Brfore Reshaping:")
print(a.shape)


# 1. Reshape to 2x3 
b = a.reshape(2,3)

print("After Reshaping 2x3:")
print(b.shape)
print(b)


# 2. Reshape to 6x1
c = a.reshape(6,1)

print("After Reshaping 6x1:")
print(c.shape)
print(c)


# 3. Reshape to 6x : vector of items without column
d = a.reshape(6, )

print("After Reshaping 6, :")
print(d.shape)
print(d)

Brfore Reshaping:
(3, 2)
After Reshaping 2x3:
(2, 3)
[[1 2 3]
 [4 5 6]]
After Reshaping 6x1:
(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
After Reshaping 6, :
(6,)
[1 2 3 4 5 6]


# Flattening

In [61]:
a = np.array([ [1,2] , [3,4] , [5,6] ])

print(a, a.shape)


result = a.ravel()

print(result, result.shape)

# Alternative for Looping
for item in a.flat:
    print(item)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)
1
2
3
4
5
6


# Iteration over an array

In [64]:
a = np.array([ [1,2] , [3,4] , [5,6] ])

print(a, a.shape)

for row in a:
    print(row)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2]
[3 4]
[5 6]


# Random

In [65]:
from numpy import random

In [95]:
x = random.randint(100)
print(x, type(x))


x = random.randint(100, size=(5,))
print(x, type(x))

x = random.randint(100, size=(3,2))
print(x, type(x))


x = random.uniform(100, size=(3,2))
print(x, type(x))


##############################
my_list = [1,2,3,4,5,6,7]

x = random.choice(my_list)
print(x, type(x))


x = random.choice(my_list, size= (3,))
print(x, type(x))


x = random.choice(my_list, size= (3,6))
print(x, type(x))


5 <class 'int'>
[72 46 35 91 96] <class 'numpy.ndarray'>
[[84 84]
 [38 21]
 [86 60]] <class 'numpy.ndarray'>
[[43.87122058 94.08575953]
 [52.0364128  96.89907657]
 [37.52654533 73.28494049]] <class 'numpy.ndarray'>
3 <class 'numpy.int32'>
[5 4 4] <class 'numpy.ndarray'>
[[3 4 6 1 5 2]
 [7 3 6 5 7 2]
 [5 7 3 1 6 1]] <class 'numpy.ndarray'>


# View

In [98]:
a = np.array([1,2,3,4,5]) 
b = a  # b will refenrece to the same container as a

print(a)
print(b)


a[0] = 11 
print(a)
print(b)


b[1] = 22 
print(a)
print(b)

[1 2 3 4 5]
[1 2 3 4 5]
[11  2  3  4  5]
[11  2  3  4  5]
[11 22  3  4  5]
[11 22  3  4  5]


# Copy

In [99]:
a = np.array([1,2,3,4,5]) 
b = a.copy() # a & b will refer to differtent containers

a[0] = 11 
print(a)
print(b)


b[1] = 22 
print(a)
print(b)

[11  2  3  4  5]
[1 2 3 4 5]
[11  2  3  4  5]
[ 1 22  3  4  5]


# Vertical Stack of data 
übereinander

In [105]:
a1 = np.array([ 
                [1,2] , 
                [3,4] , 
                [5,6] 
            ])

a2 = np.array([ 
                [7,8] , 
                [9,10] , 
                [11,12] 
            ])

output = np.vstack((a1, a2))

print(output)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


# Horizontal Stacking of data
nebeneinander

In [101]:
a1 = np.array([ 
                [1,2] , 
                [3,4] , 
                [5,6] 
            ])

a2 = np.array([ 
                [7,8] , 
                [9,10] , 
                [11,12] 
            ])

output = np.hstack((a1, a2))

print(output)

[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


# Transpose

In [102]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

output = a.T 

print(output)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Where ..-> show the indexes where arrays matchs a logic

In [103]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])

# Show the indexes where a == b
print(np.where(a == b))


(array([0, 3, 4], dtype=int64),)
